### ISSUE TITLE
Borg backup reports "The backup miserably failed to backup monitorix application."

### ISSUE THREAD

**Issue by olberger** [YunoHost-Apps/monitorix_ynh#60]
I'm using the Borg YNH app to manage backups with borg.

Every time backups are made, I get a report by mail, sent by the borg backup app, with:
```
The backup miserably failed to backup monitorix application.

[...]
Collecting files to be backed up for monitorix…
Declaring files to be backed up...
Backing up code...
Backup script completed for monitorix. (YunoHost will then actually copy those files to the archive).
Creating a backup archive from the collected files…
The archive will contain about 684.4MB of data.
The operation 'Create a backup archive' could not be completed. Please share the full log of this operation using the command 'yunohost log share XXXX' to get help
```

In such a blog file (not provided in details cause it contains confidential details), I can spot:
```
[...]
2024-05-29 07:04:13,422: DEBUG - [2024-05-29_07:03:48] apps/monitorix/backup/home/yunohost.app/monitorix/pgsql.rrd: file changed while we backed it up
2024-05-29 07:04:13,423: DEBUG - [2024-05-29_07:03:48] apps/monitorix/backup/home/yunohost.app/monitorix/phpfpm.rrd: file changed while we backed it up
2024-05-29 07:04:14,425: ERROR - Could not run script: /etc/yunohost/hooks.d/backup_method/05-borg_app
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/hook.py", line 298, in hook_callback
    hook_return = hook_exec(
  File "/usr/lib/python3/dist-packages/yunohost/hook.py", line 416, in hook_exec
    raise YunohostError("hook_exec_failed", path=path)
yunohost.utils.error.YunohostError: Could not run script: /etc/yunohost/hooks.d/backup_method/05-borg_app
```
There are additional errors/warnings regarding the destination Bog server, but which aren't relevant here AFAIU.

It isn't exactly easy to trace the source of errors reported here, as it's a "custom" backup method, provided to YNH by borg-ynh, with lots of stdout/stderr redirections and such.

Still, I guess the issue may be related to the message displayed by borg about the rrd files being changed while backed-up.

Or maybe there's another error, which is masked somewhere during the chain of invocations.

I'm not sure the issue is in borg, in monitorix, or in a custom way of performing the backup that should be stated somewhere so that borg can take advantage of it.

Your help is very much welcome.

**Comment by olberger** [comment]
FWIW, I deactivated the backup of the data, following instructions at: https://yunohost.org/ru/backup/include_exclude_files#do-not-backup-large-amoun

Suboptimal, but at least then, I don't get reports by mail at each automatic backup

**Comment by Josue-T** [comment]
Hello,

Short answer: you must stop `monitorix.service` while do you the backup.

Long answer:

To me it's bad to backup an app while the app is running for this raison and also for data integrity. Note that while you do a backup of this app while the service is running (with `yunohost backup ...`), you will have a warning which say that it's recomended to stop the service (`monitorix.service` in this case) when you do the backup.

**Comment by olberger** [comment]
Valid point, @Josue-T, and indeed, the warning occurs ... however, a monitoring system wouldn't be as usefull if stopped for some recurring periods (may generate holes in the curves, stats ?)... maybe the backup could ideally be working on a RO snapshot and not be troubled by files being modified... in any case, this needs to be addressed in a uniform way in YNH, IMHO. 

Actually, there may be such a snapshotting mechanism out of the box ?

Given the way the current config for borg_ynh works (it seems), the backups are made every hour or so, which would clearly be inconvenient if every backup would halt monitorix.

I hope others can have a better overview of the backup system design in YNH to provide more ideas/patches. I guess the current implementation of borg_ynh may be greatly improved with further tuning options, etc.
