### ISSUE TITLE
Installing another app issues errors linked to monitorix

### ISSUE THREAD

**Issue by olberger** [YunoHost-Apps/monitorix_ynh#63]
I have installed Element on our YNH instance, where Monitorix is installed, and got some errors.

It appears that these errors are linked to execution of Monitorix-related scripts. The problems arise after execution of /opt/yunohost/monitorix/update_config_if_needed.sh, right after the :
```2024-07-09 18:11:45,089: INFO - [####################] > Installation of element completed
2024-07-09 18:11:45,091: DEBUG - + ynh_exit_properly
```
I can spot:
`ynh_package_is_installed: command not found` and also (rest of the logs includes sensitive infos):
```
2024-07-09 18:12:02,196: DEBUG - + ynh_store_file_checksum --file=/etc/nginx/conf.d/monitorix_status.conf
2024-07-09 18:12:02,204: WARNING - md5sum: unrecognized option '--file=/etc/nginx/conf.d/monitorix_status.conf'
2024-07-09 18:12:02,206: WARNING - Try 'md5sum --help' for more information.
2024-07-09 18:12:02,493: DEBUG - + configure_db
2024-07-09 18:12:02,494: DEBUG - + false
2024-07-09 18:12:02,494: DEBUG - + false
2024-07-09 18:12:02,494: DEBUG - + false
2024-07-09 18:12:02,494: DEBUG - + ynh_systemd_action --service_name=monitorix --action=restart --log_path=systemd '--line_match= - Ok, ready.'
2024-07-09 18:12:02,501: WARNING - /opt/yunohost/monitorix/update_config_if_needed.sh: line 85: ynh_systemd_action: command not found
2024-07-09 18:12:02,501: DEBUG - + ynh_exit_properly
2024-07-09 18:12:02,501: DEBUG - + local exit_code=127
2024-07-09 18:12:02,502: DEBUG - + [[ install =~ ^install$|^upgrade$|^restore$ ]]
2024-07-09 18:12:02,504: DEBUG - + '[' 127 -eq 0 ']'
2024-07-09 18:12:04,013: ERROR - Could not run script: /etc/yunohost/hooks.d/post_app_install/50-monitorix
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/hook.py", line 298, in hook_callback
    hook_return = hook_exec(
  File "/usr/lib/python3/dist-packages/yunohost/hook.py", line 416, in hook_exec
    raise YunohostError("hook_exec_failed", path=path)
yunohost.utils.error.YunohostError: Could not run script: /etc/yunohost/hooks.d/post_app_install/50-monitorix
```

Hope this helps.

**Comment by Josue-T** [comment]
should be fixed by https://github.com/YunoHost-Apps/monitorix_ynh/pull/62
